### ISSUE TITLE
Build failing on "invalid version string"

### ISSUE THREAD

**Issue by wodger1912** [jellyfin/jellyfin-plugin-tvdb#18]
Following the instructions, I have .NET core for arch installed - get this error when starting to build:

/usr/share/dotnet/sdk/3.1.108/NuGet.targets(123,5): error : '10.*-*' is not a valid version string. [/home/wodger/Downloads/Jellyfin_TVDB/Jellyfin.Plugin.Tvdb.sln]

Would like to get this working if possible

Thanks

**Comment by crobibero** [comment]
Plugins are now built using dotnet 5.
https://dotnet.microsoft.com/download/dotnet/5.0
