### ISSUE TITLE
Metadata for TV shows

### ISSUE THREAD

**Issue by undead9786** [jellyfin/jellyfin-plugin-tvdb#22]
**Describe the bug**
Jellyfin 1.6.4 used to edit the metadata of TV shows but no longer does it in 1.7.0. I started using rc3 and noticed the issue and there was a bug report in github that you could open the metadata sub folders in rc3 and rc4 fixed that but still has the issue where it doesn't edit the metadata of TV shows but movies is fine.

Took a screenshot of episodes set by date they were put into jellyfin, Stargate episodes were during 1.6.4 and Top Gear is from 1.7.0 rc4
https://imgbox.com/u7AhawqF

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: N/A
 - Clients: N/A
 - Browser: N/A
 - Jellyfin Version: 1.7.0 rc4
 - Playback: N/A 
 - Installed Plugins: N/A
 - Reverse Proxy: N/A
 - Base URL: [e.g. none, yes: /example]
 - Networking: N/A
 - Storage: N/A

**To Reproduce**

1. Add a TV Show

**Expected behavior**
Edit metadata of the TV Show or episode

**Logs**
If logs are needed please let me know what to do to get what you need.

**Screenshots**
https://imgbox.com/u7AhawqF

**Additional context**
N/A

**Comment by mooninite** [comment]
Thanks for the fix. Could a release be pushed?

**Comment by crobibero** [comment]
> 
> 
> Thanks for the fix. Could a release be pushed?

Tagged a new release, should be up shortly

**Comment by crobibero** [comment]
Plugin release is in the repo, may take a little more for everything to sync up
