### ISSUE TITLE
Update for API v4 support

### ISSUE THREAD

**Issue by crobibero** [jellyfin/jellyfin-plugin-tvdb#47]
SDK: https://www.nuget.org/packages/Tvdb.Sdk
Deadline: ~Oct 1, 2021~ First half of 2022

**Comment by mmBesar** [comment]
This update is very much needed, thanks.

**Comment by sgtaziz** [comment]
Is there any progress on this?

**Comment by crobibero** [comment]
Not that I know of. Upgrading to the v4 api is essentially a rewrite of the plugin.
