### ISSUE TITLE
The episode is shown as missing but it's not!

### ISSUE THREAD

**Issue by Ctrl-X1** [jellyfin/jellyfin-plugin-tvdb#87]
Hello, 
So as the title says, literally all my episodes in all series that I have shown as missing but they are available. I checked the tvdb ID and it's the same in both episodes the missing one and the available.
Any help?

![لقطة الشاشة 2023-05-06 005942](https://user-images.githubusercontent.com/77636440/236575674-549179a6-e324-45a3-9b4e-0f6a487592dd.png)

**Comment by surjava56351** [comment]
Is there an update for this issue? Its so irritating that I am having to refrain from using it in Jellyfin,
